name: Nodes Engineering
title: Nodes Engineering Blog
subtitle: Engineering Awesome
description: Leading digital product development agency with expert in-house developers that develop enterprise-grade digital products for leading brands.
author: Nodes Agency
image: /assets/img/header/nodes-agency-team.jpg
locale: en_GB
url: https://engineering.nodesagency.com
social:
  twitter:
    username: Nodes_Apps

sass:
  sass_dir: assets/css

source: src
destination: dist

new_post_name: :year-:month-:day-:title.md

defaults:
  -
    scope:
      path: "_posts"
    values:
      permalink: /categories/:categories/:year/:month/:day/:title
      layout: "post"
  -
    scope:
      path: "_authors"
    values:
      permalink: /authors/:author_id
      layout: "author"
      image : /assets/img/header/author.jpg

collections:
  authors:
    title: Authors
    output: true

marked:
  gfm: true
  tables: true
  smartypants: true

plugins:
  - jekyll-paginate-v2

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

pagination:
  enabled: true
  per_page: 10
  permalink: '/page/:num/'
  title: ' - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  trail:
    before: 1
    after: 1
